// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiKey.openai": string;
      "apiKey.gemini": string;
      "apiKey.deepseek": string;
      "apiKey.openrouter": string;
      "baseURL.openai": string;
      "customModel.openai": string;
      "baseURL.deepseek": string;
      "customModel.deepseek": string;
      "baseURL.openrouter": string;
      "customModel.openrouter": string;
    };
  }
}
